# Represents the database workload logging (small sequential writes)
logging:
  matrix:
    number_threads: [ 1, 2, 4, 8, 16, 32 ]
    # ~[168 mil ops, 84 mil ops, 42 mil ops, 21 mil ops, 10 mil ops]
    access_size: [ 64, 128, 256, 512, 1024 ]
    persist_instruction: [ nocache, none ]

  args:
    total_memory_range: 10G
    exec_mode: sequential
    write_ratio: 1

logging_partition:
  matrix:
    number_partitions: [ 1, 2, 4, 8 ]
    # [168 mil ops, 84 mil ops, 42 mil ops, 21 mil ops, 10 mil ops]
    access_size: [ 64, 128, 256, 512, 1024 ]
    persist_instruction: [ nocache, none ]

  args:
    total_memory_range: 10G
    number_threads: 8
    exec_mode: sequential
    write_ratio: 1
