large_seq_read:
  matrix:
    # Run with these thread counts
    number_threads: [1, 2, 4, 8, 16, 24, 32, 36]
    # Run with 64 Byte access to 16/256 KiB and 1 MiB.
#    access_size: [64, 256, 1024, 4096, 16384, 262144, 1048576]
    access_size: [256, 4096]
  args:
    total_memory_range: 53687091200  # 50 GiB
#    total_memory_range: 67108864  # 64 MiB
    exec_mode: sequential
    read_ratio: 1
    write_ratio: 0
