large_persistent_copy:
  matrix:
    number_threads: [ 1, 2, 4, 8, 16, 32 ]
    access_size: [ 10485760, 104857600, 1073741824 ] # [10 MiB, 100 MiB, 1 GiB]
    persist_instruction: [ ntstore, none ]

  args:
    total_memory_range: 107374182400 # 100 GiB
    exec_mode: sequential
    read_ratio: 0
    write_ratio: 1
